### ISSUE TITLE
FYI - scdb is semi-recognized already

### ISSUE THREAD

**Issue by dolkensp** [richardthombs/scdb#1]
/u/malogos already has http://starcitizendb.com/ which is also known as `scdb` in some circles, and it also has an api, and has been well maintained for a few years now.

If you're not attached to the name, it may be an idea to rebrand before you go wide/public - perhaps scapi? Could even spin things a bit into "SCnAPI", (Star Citizen Normalized API) and have a little crocodile as a mascot/logo etc =D

**Comment by richardthombs** [comment]
Lol thanks, I will change it

**Comment by alistair3149** [comment]
FYI, [SC API](https://starcitizen-api.com/) is also a semi-recognized name that is well maintained as well.

**Comment by dolkensp** [comment]
I've got the domains starcitizen.watch and starcitizen.fans.

Could potentially work out something to become known as the "fan api" under starcitizen.fans if you're interested.

**Comment by alistair3149** [comment]
@dolkensp hmm fans might not be great at SEO, also with the word starcitizen in the domain name you might want to run through it with CIG, they are picky with the recent fankit

**Comment by richardthombs** [comment]
Peter, if you don't mind, I'm thinking of scunp4ked.com or scunpaked.com? Or scunpacked.com :)

**Comment by dolkensp** [comment]
No objections here @richardthombs - I was just giving you a heads-up - I'm certainly no arbiter of name rights!

**Comment by richardthombs** [comment]
New home is https://scunpacked.com. I will change the name of the repo soon too.
